schema_version = "1.0.0"
id = "CyclesBaker"
version = "2.0.3"
name = "Cycles Baker"
tagline = "UI for baking with Cycles."
maintainer = "JoseConseco"
type = "add-on"
website = "https://joseconseco.github.io/GroupProDocs/"
tags = ["Object"]
blender_version_min = "4.4.0"

# blender_version_max = "5.1.0"

# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [ "SPDX:GPL-2.0-or-later"]
 copyright = [ "2024 Bartosz Styperek", ]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]


# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #

[permissions]
network = "To look for and install updates."
# files = "To save presets into library."
# clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
